runtime: python
env: flexible
service: pythonapi

runtime_config:
    python_version: 3.7

entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
